### ISSUE TITLE
RankLLM in LlamaIndex + LangChain

### ISSUE THREAD

**Issue by ronakice** [castorini/ura-projects#29]
Integration can bring up usage!

**Comment by xpbowler** [comment]
working on this

**Comment by lintool** [comment]
This has been done! See https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/rankLLM/

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Everyone building advanced RAG should carefully consider the reranker they want to use. Hint: Use an LLM (specifically RankZephyr) 💡<br><br>We’re excited to feature RankLLM by <a href="https://twitter.com/rpradeep42?ref_src=twsrc%5Etfw">@rpradeep42</a> et al. - an awesome collection of open-source LLMs finetuned for reranking 💫, achieving… <a href="https://t.co/2bL6TfbISr">pic.twitter.com/2bL6TfbISr</a></p>&mdash; LlamaIndex 🦙 (@llama_index) <a href="https://twitter.com/llama_index/status/1775166279911186930?ref_src=twsrc%5Etfw">April 2, 2024</a></blockquote>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">RankZephyr is a nice 7B model by <a href="https://twitter.com/rpradeep42?ref_src=twsrc%5Etfw">@rpradeep42</a> et al. that is optimized for list-wise zero-shot reranking. Since it is much smaller than proprietary models, it is a big step towards practically using LLMs as part of production retrieval systems (as opposed to simply combining LLM… <a href="https://t.co/CmW35PA0HH">https://t.co/CmW35PA0HH</a> <a href="https://t.co/8DPPIy0vy7">pic.twitter.com/8DPPIy0vy7</a></p>&mdash; Jerry Liu (@jerryjliu0) <a href="https://twitter.com/jerryjliu0/status/1775306002025599282?ref_src=twsrc%5Etfw">April 2, 2024</a></blockquote>

I'm sure there will be follow-up, but closing issue for now.
